# Uncomment the next line to define a global platform for your project
platform :ios, '8.4'

target 'RNAuthorizeNet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RNAuthorizeNet
  pod 'AuthorizeNetAccept', '~> 0.4.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
       if target.name == 'AuthorizeNetAccept'
         target.build_configurations.each do |config|
           config.build_settings['SWIFT_VERSION'] = '4.0'
         end
       end
  end
end
